Conste struct devices for Zephyr 2.4.
lastmileICT/SIM800-AT pull request #14
Opened 2020-10-20 14:21 UTC by daniel-connectedenergy

Zephyr 2.4 support.

2020-10-20 14:50 UTC, martinjaeger requested changes

2020-10-20 14:50 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +void read_resp(const device *dev, void* user_data)
Missing `struct`?

2020-10-26 09:50 UTC, azeemshatp commented
So, are we going to leave this branch in parallel?

2020-10-26 10:33 UTC, daniel-connectedenergy commented
I need to find some time to squeeze in a day of work to make sure this works properly - this means also fixing the CI.

2020-11-09 17:55 UTC, martinjaeger approved these changes

2020-11-09 17:57 UTC, martinjaeger commented
From my point of view, we can make master compatible to Zephyr 2.4 and if necessary create a 2.3 branch to track from SB if there is any reason for not switching to v2.3 in SB.

If anyone disagrees, please leave comments here.

2020-11-09 18:01 UTC, JordanSilverman commented
It's fine by me. @azeemshatp maybe you could have a look at upgrading SB to zephyr 2.4? I don't know what the process is.

2020-11-09 18:03 UTC, martinjaeger commented
Ok, if @azeemshatp agrees I will merge this so that I can create the other PR in cloudsolar firmware.

2020-11-09 18:04 UTC, daniel-connectedenergy commented
I concur - we should move to Zephyr 2.4.

2020-11-09 18:32 UTC, merged