Implement FTPEXTGET functionality
lastmileICT/SIM800-AT pull request #17
Opened 2020-12-10 14:29 UTC by azeemshatp

What does this PR do?
Implements the "FTP extend get" functionality to download a file from an FTP server using the command AT+FTPEXTGET. The final response from the SIM800 modem will be as below, 
+FTPEXTGET: 1,0

This helps to store the downloaded files into the SIM800 RAM instead of using the SIM800 system flash. Useful in memory constrained GSM modules. The final response from the modem can take nearly 1 minute, and hence, the calling function will have to wait for this.

2020-12-10 15:31 UTC, daniel-connectedenergy requested changes
I believe reusing SIMCOM's terminology is not ideal, FTPEXTGET is not
a very memorable name for us to insert into our APIs. I would rather
have friendlier names in our API such as `ftp_get_to_ram`,
`ftp_check_dl_complete`, `ftp_read_from_ram`.

If not used at the moment and to avoid confusion, maybe get rid of
`ftp_get` and `read_ftp_file` functions - given the small flash size
we might never use those.

I am confused by the documentation as well as by this code whether the
file size can be retrieved reliably. I understand from the manual that
after starting the download, one should issue periodically the command
`AT+FTPEXTGET?` to get the download status and the current byte count
in a reply of the form: `+FTPEXTGET: <status>[,<receivedLength>]`. I
understand that the `status` flag would be 0 if the download was
finished, otherwise if it's 1, then the download is not finished and
the file size is partial. 

I would thus rename the `ftp_ext_get_filesize` function to
`ftp_check_dl_complete` and make it return a boolean and accept a
parameter as an integer reference where it's going to store the
current byte count.

I have this usage pattern in mind, so correct me if I'm wrong:

```
bool ftp_check_dl_complete(uint16_t &size);

uint16_t file_size;
size_t block_size = 4096;

ftp_get_to_ram(&server, &user, *pwd, &fname, &path); // btw: filename and path can be combined
while(!ftp_check_dl_complete(file_size)) {
    k_sleep(K_SECONDS(6));
}
for(size_t i=0; i < file_size/block_size; i++) {
    ftp_read_from_ram(i, block_size);
    // The original function ftp_ext_file_read baffles me a bit because
    // I can't figure out from its signature nor from its dosctrings where
    // in fact does the data go (no buffer specified) - I suspect a lot of
    // other functions behave the same.

    (...) // do stuff with the data, e.g verify image or write to flash
}

...

2020-12-10 16:49 UTC, azeemshatp commented
Thanks for the comments @daniel-connectedenergy .
I will consider the function renaming.

Regarding the other point: We need not periodically issue the command AT+FTPEXTGET?, instead we can just wait for a final string "+FTPEXTGET: 1,0" that tells us that a download has completed.
http://www.microchip.ua/simcom/SIM800x/Application%20Notes/SIM800%20Series_IP_Application%20Note_V1.05.pdf

2020-12-10 16:58 UTC, daniel-connectedenergy commented
Ok, so once `ftp_get_to_ram(...)` has been fired, we just need to sleep and periodically check for an unsolicited response code from the modem that says `+FTPEXTGET: 1,0` ?

Can you please post a realistic usage snippet just like the one I've put above so I can understand how the library is going to be used then ?

2020-12-10 17:16 UTC, azeemshatp commented
LOG_DBG("Waiting to complete downloading...%d", fail_count);
                    if (strlen(resp_buf) != 0) { // If the buffer is not empty
                        char *ptr = strstr(resp_buf, "+FTPEXTGET: 1,0");
                        if (ptr != NULL) {
                            // Success. So get the file size and move to the next state.
                            LOG_INF("Download successful.");

                            size_new_app = SIM800.ftp_ext_get_filesize();
                            if (size_new_app == MODEM_RESPONSE_ERROR) {
                                LOG_INF("ERROR: Invalid file size");
                                return;
                            }
                            LOG_INF("File size = %d ", size_new_app);
                               ...................................
                        }
                        else { // On error response
                            if ((strstr(resp_buf, "+FTPEXTGET:") != NULL) ||
                                (strstr(resp_buf, "+CME ERROR:") != NULL)) {
                                LOG_INF("ERROR downloading");
                                // End the wait state
                                fail_count = wait_seconds;
                            }
                            return;
                        }
                    }

2020-12-11 11:58 UTC, daniel-connectedenergy commented
It partially makes sense - the code as I see is pasted from the working GSM state machine. It's incomplete in the sense it only deals with the waiting, the `ftp_get_to_ram` and `ftp_read_from_ram` are not included. I had a look at https://github.com/lastmileICT/cloudsolar-node-firmware/blob/cloudsolar/src/custom/gsm.cpp and I believe at some point issue #79 (https://github.com/lastmileICT/cloudsolar-node-firmware/issues/79) needs to be addressed.

2020-12-11 13:59 UTC, azeemshatp commented
Sorry that the above snippet did not cover all the functions. Here is it in case if you would like to have a look it again.
As you rightly mentioned, we need to disentangle OTA from the GSM code at some point soon.

ftp_get_to_ram() snippet:

	case GSM_OTA_DOWNLOAD_BINARY:
		fail_count++;
		if (fail_count >= 3) {
			fail_count = 0;
			LOG_DBG("Could not download binary, so skipping this");
			gsm_state = GSM_STATE_CLOSE_BEARER;
			return;
		}
		LOG_INF("Downloading new firmware");
		// Downloading can take upto 1 minute in the background, but is handled internally by
		// the SIM800 module. Hence, will not trigger the WDT.
		if (SIM800.ftp_get_to_ram(CONFIG_FTP_SERVER, CONFIG_FTP_UN, CONFIG_FTP_PW,
				CONFIG_FTP_FILE_NAME, CONFIG_FTP_FILE_PATH) == MODEM_RESPONSE_ERROR) {
			return;
		}
		LOG_DBG("Download initiated... ");

		// Wait until the file is downloaded successfully
		gsm_state = GSM_STATE_WAIT;
		wait_download_binary = true;
		wait_seconds = 240; // 4 minutes
		break;
		
		
Waiting and ftp_get_ram_filesize() snippet:

	if (wait_download_binary) { // Waiting response for FTPEXTGET
		LOG_DBG("Waiting to complete downloading...%d", fail_count);
		if (strlen(resp_buf) != 0) { // If the buffer is not empty
			char *ptr = strstr(resp_buf, "+FTPEXTGET: 1,0");
			if (ptr != NULL) {
				// Success. So get the file size and move to the next state.
				LOG_INF("Download successful.");

				size_new_app = SIM800.ftp_get_ram_filesize();
				if (size_new_app == MODEM_RESPONSE_ERROR) {
					LOG_INF("ERROR: Invalid file size");
					return;
				}
				LOG_INF("File size = %d ", size_new_app);

				........................

				gsm_state = GSM_STATE_CLOSE_BEARER;
				fail_count = 0;
				wait_download_binary = false;
				break; // To go to the next state
			}
			else { // On error response
				if ((strstr(resp_buf, "+FTPEXTGET:") != NULL) ||
					(strstr(resp_buf, "+CME ERROR:") != NULL)) {
					LOG_INF("ERROR downloading");
					// End the wait state
					fail_count = wait_seconds;
				}
				return;
			}
		}
		return; // Keep waiting
	}



ftp_read_from_ram() snippet:

    for (int i = 0; i < max_num_flash_pages; i++) {
        SIM800.ftp_read_from_ram(FLASH_PAGE_SIZE, offset);
		
		..............................

        // writing FLASH_PAGE_SIZE number of bytes
        write_flash_page(&resp_buf[buf_offset], dest_address);

        offset += FLASH_PAGE_SIZE;
        dest_address += FLASH_PAGE_SIZE;

        k_sleep(K_MSEC(1));
    }

2020-12-11 15:07 UTC, daniel-connectedenergy commented
I wouldn't mind if you also removed `read_ftp_file` as suggested earlier and maybe also rename `ftp_ext_end_session` to `ftp_end_session` (this still leaks the `ext` implmentation detail to the caller).

2020-12-11 15:09 UTC, azeemshatp commented
I have now renamed the RAM access functions @daniel-connectedenergy .
I have kept the older functions ftp_get() and read_ftp_file() functions as it is, for the time being. However, I will rename them to ftp_get_to_flash() and  ftp_read_from_flash() respectively, when I update the OTA code in cloudsolar firmware next week.

2020-12-14 14:55 UTC, JordanSilverman reviewed
Just a couple of questions 👍

2020-12-14 14:55 UTC, JordanSilverman commented on src/SIM800-AT-Zephyr.cpp
> +    k_sleep(K_SECONDS(1));
Is that enough time? Even when reading the larger page sizes for the NGC?

2020-12-14 14:55 UTC, JordanSilverman commented on src/SIM800-AT-Zephyr.cpp
> +    send_cmd("AT+FTPEXTGET=1", 90, NULL); //Takes more than 1 minute to download
Is 90 seconds long enough in places with bad connectivity?

2020-12-14 15:04 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +    k_sleep(K_SECONDS(1));
My feeling is that this should be sufficient. But I still need to test this in NGC. I am currently porting the same code there, and will do the testing tomorrow. I think it will only need a slight tuning.

2020-12-14 15:08 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +    send_cmd("AT+FTPEXTGET=1", 90, NULL); //Takes more than 1 minute to download
It's usually 35-40 seconds for images of size = 93892 bytes. I have already kept almost double of that now. I hope this should be enough, but this needs to be confirmed during system testing at poor network conditions.

2020-12-14 15:12 UTC, JordanSilverman commented on src/SIM800-AT-Zephyr.cpp
> +    send_cmd("AT+FTPEXTGET=1", 90, NULL); //Takes more than 1 minute to download
okay, 1 more question - do we definitely need to k_sleep for so long after every command even though we have the timeout in the send_cmd function?

2020-12-14 15:54 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +    send_cmd("AT+FTPEXTGET=1", 90, NULL); //Takes more than 1 minute to download
Yes, we have to keep this. The timeout in the send_cmd() mainly decides how long the Rx interrupt is to be kept enabled. And this happens in the background in the ISR. Whereas k_sleep() introduces an absolute delay blocking the current thread. If we don't have this delay, sometimes we get the resp_buf only partly filled.

2020-12-14 16:38 UTC, azeemshatp commented
> I wouldn't mind if you also removed `read_ftp_file` as suggested earlier and maybe also rename `ftp_ext_end_session` to `ftp_end_session` (this still leaks the `ext` implmentation detail to the caller).

This is now done @daniel-connectedenergy. As discussed in the meeting today the older functions for flash access are kept as it is, for the time being.

2020-12-14 16:42 UTC, JordanSilverman approved these changes
LGTM

2020-12-14 17:15 UTC, daniel-connectedenergy approved these changes
All good !

2020-12-14 17:16 UTC, merged