Request more data from the network
lastmileICT/SIM800-AT pull request #19
Opened 2021-04-21 15:04 UTC by azeemshatp

Make the TCP send data size multiples of 200 to request for more data from the network/modem. Also add a config to change this value.

2021-04-22 06:15 UTC, martinjaeger requested changes
Why not just specify the amount of data to request directly? Now we specify a multiplier for a magic number of 200 to determine the amount of data to receive... a bit confusing in my opinion.

Also please namespace the Kconfig variables properly. `CONFIG_MSG_MULT` does sounds very generic. Prefix with something like `CONFIG_SIM800_` to make clear where this thing belongs to.

2021-04-22 13:31 UTC, azeemshatp commented
Both the suggestions are updated now

2021-04-30 11:34 UTC, daniel-connectedenergy approved these changes
LGTM !

2021-04-30 11:44 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +
Maybe I don't understand this correctly, but isn't this whole thing equivalent to just keeping the previous line and increasing `200` to `1460`??

And should this not be limited to `sizeof_resp_buf`? What happens if we receive more than what fits into the buffer later?

2021-04-30 13:04 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +
Actually it's not. I tried using sizeof_resp_buf, and then realized during testing that for NGC this would not work. We will then be asking for 2048 bytes of data, for which SIM800 will return a 0, since the maximum allowed length of data is only 1460. So I had to keep it this way. 
Also it is no more configurable, since I have removed that the macro definition from the Kconfig, so it's not the same as before.

2021-04-30 13:11 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +
1. If the SIM800 can return max. 1460 bytes, why do we have a buffer of 2048 bytes in the NGC where the last 588 bytes will never be used? Or did I misunderstand something?
2. What's the point of writing a constant preprocessor define into a char buffer on the stack with `snprintf` instead of using a string constant directly?

2021-04-30 13:38 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +
1. As far as I can understand, the limitation of 1460 bytes is only for the command "AT+CIPRXGET=2,%d", and not for many other AT commands, which can return more bytes. For example, the FTP read (AT+FTPEXTGET) used during OTA can read 2048 bytes. 
The function request_data() is only used in the specific case of manual data request, during MQTT processing. We should probably rename the function to avoid confusion then.

2. I preferred to use a meaningful name for this value, so as to not look like a magic number :). But I can change it if you don't think that's required.

2021-04-30 13:43 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +
I think I will get rid of the snprintf. Thanks

2021-04-30 13:45 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +
1. Ok, understood.
2. Meaningful names are good if the compiler can handle them and convert them into efficient code. But that's not the case here as far as I can see. So please keep the comment and use a constant string instead of expensive string processing functions.

2021-04-30 15:25 UTC, martinjaeger approved these changes

2021-04-30 15:26 UTC, merged