Make ip_rx_data() more robust to edge cases.
lastmileICT/SIM800-AT pull request #23
Opened 2022-11-01 15:20 UTC by mcqtom

- Dont allow packet lengths SIM800 cant deal with. If you request 0 or >1460 you get an error response which this function is not prepared for.
- Return TCP avail so that caller knows there is still data available even though only a fixed amount may be delivered due to buffer constraints.
- Make scanning for the CIPRXGET independent of position as unexpected behaviour when SIM800_ACK_TCP_TX=y

2022-11-01 16:27 UTC, JordanSilverman approved these changes

2022-11-01 17:10 UTC, daniel-connectedenergy requested changes
Thanks Tom, makes sense - there are though two minor nitpicks that I've pointed out.

2022-11-01 17:10 UTC, daniel-connectedenergy commented on src/SIM800-AT-Zephyr.cpp
> +    if(tcp_packet_len > 1460) tcp_packet_len = 1460;
Please use curlies for one liners, eg:

```suggestion
if(tcp_packet_len > 1460) {
    tcp_packet_len = 1460;
}
```

2022-11-01 17:10 UTC, daniel-connectedenergy commented on src/SIM800-AT-Zephyr.cpp
> +    if(tcp_packet_len == 0) return 0;
Just as above:

```suggestion
if(tcp_packet_len == 0) {
    return 0;
}
```

2022-11-02 13:51 UTC, mcqtom commented
This now also includes modem response stripping as part of SIM800 library

2022-11-02 14:39 UTC, daniel-connectedenergy approved these changes
Looks good to me !

2022-11-02 14:50 UTC, merged