Redesign the UART communication using interrupts
lastmileICT/SIM800-AT pull request #9
Opened 2020-09-24 09:46 UTC by azeemshatp

What does this PR do?
The UART reception from the GSM modem is now handled using serial interrupts.

Where should the reviewer start?
SIM800-AT.cpp

Any background context you want to provide?
The interrupt driven code is only implemented for the Zephyr framework now. The mbed version will done in a separate PR. Hence, the mbed part of the code has been placed in a #ifdef for now and will be changed later.

2020-09-24 16:10 UTC, JordanSilverman reviewed
Seems fine to me but I thought the idea of it being interrupt driven would speed up the processing. As soon as we receive the expected characters we can carry on with the function instead of waiting for so long inside each function. I don't have a suggestion how to fix that but it would make sense.

2020-09-24 16:10 UTC, JordanSilverman commented on src/SIM800-AT.h
> +#ifdef __MBED__
Why don't you put all the mbed functions together and all the Zephyr functions together to reduce the number of ifdefs?

2020-09-24 16:18 UTC, martinjaeger requested changes

2020-09-24 16:18 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +    send_cmd("AT+SAPBR=1,1", 65, NULL); // Response time can be upto 85 seconds
Comment says 85 seconds, but timeout set to 65. Why?

2020-09-24 16:18 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +        // token = strtok(bearer_info, delimiters);
Delete this line.

2020-09-24 16:18 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +    send_cmd("AT+CIPSHUT", 6, NULL); // Can take up to 65 seconds
Comment doesn't match timeout.

2020-09-24 16:18 UTC, martinjaeger commented on src/SIM800-AT.h
> -     * @param size_buf Size of the receive buffer
Well, these buffers are still present for the mbed code... but as they will be removed in the future I'm fine with removing the comments already.

2020-09-24 16:18 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +            printf("\r\nFailed init_resp\r\n");
`DEFAULT_TIMEOUT` is passed to the `send_cmd` function, but then we wait only 1s (hard-coded and less than `DEFAULT_TIMEOUT`) until the message is processed (checked if we received an ACK)? That doesn't make sense to me.

(same for several of other locations below)

2020-09-24 16:23 UTC, JordanSilverman commented on src/SIM800-AT-Zephyr.cpp
> +                printf("Buffer size exceeded\r\n");
Out of interest, why is this?

2020-09-24 16:48 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +                printf("Buffer size exceeded\r\n");
An ISR runs at higher priority than any thread. So it should finish as fast as possible. Printing something to the serial is very slow.

We should actually check if the ISR priority of the UART is lower than that of the DMA interrupt, which is where the control runs in. Otherwise this printf could block the control algorithm.

2020-09-24 16:54 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +                printf("Buffer size exceeded\r\n");
Oops, seems like this is not the case. Good that we talked about it. AFAIC the position in the NVIC determines the priority (lower number being higher priority). The control function is called via DMA2, which has a higher number (see e.g. [here](https://raw.githubusercontent.com/zephyrproject-rtos/hal_stm32/master/stm32cube/stm32g4xx/soc/stm32g474xx.h). @daniel-connectedenergy  do you know if the NVIC number determines priority?

There is also a dedicated priority setting which (I guess) overrules the rank in the NVIC. Will double-check if this is configurable for the callbacks in Zephyr. But the easiest would be to switch to DMA1 for ADC2 (doing the current measurement).

2020-09-25 09:37 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +    k_sleep(K_SECONDS(1));
I had checked this and seen a different response. There seems to be often a need for waiting for the response for the first AT command (I was thinking to increase this delay to some 3-4 seconds). I think this could possibly be the reason why we often get the below response even in the mbed code.

EEPROM: Empty or data layout version changed
Detected single battery (14.40 V max)
Waking up
Waking up
Waking up
Waking up
Echo off
Pin done

2020-09-25 09:39 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +    k_sleep(K_SECONDS(1));
But if I add more delay here, we need to move the wakeup part to a different state itself, otherwise WDT will trigger

2020-09-25 09:56 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +    // as described in send_cmd().
It's described in the header file SIM800-AT.h

2020-09-25 10:04 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +uint32_t size_buf = BUF_SIZE_DEFAULT;
Thanks for finding this, I forgot to change it. Initially the idea was to pass arguments to the ISR and this was planned to be used there. Will change this now.

2020-09-25 10:06 UTC, JordanSilverman commented on src/SIM800-AT-Zephyr.cpp
> +    k_sleep(K_SECONDS(1));
I was actually wrong, it needs more than 100ms so 1s should be more than enough:

There are two caveats when you want to quit sleep mode in mode 2:
1, You should input some characters (at least one) to awake module
2, An interval time of 100ms more is necessary between waking characters
and following AT commands,otherwise the waking characters will not be
discarded completely,and messy codes will be produced which may leads to
UART baudrate re-adaptation. 

If you're in sleep mode do you receive an 'OK' from the SIM800 after sending AT? I don't think so...

2020-09-25 10:14 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +                printf("Buffer size exceeded\r\n");
Agreed. Yes, I think the interrupt priority is determined based on the numbers mentioned in the IRQn_Type, so the control algorithm wont be blocked anyway.  So I don't have to do anything other than deleting the printf from here, right?

2020-09-25 10:44 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +    k_sleep(K_SECONDS(1));
Alright. Thanks for clarifying this. I will then leave it to 1 second now.

2020-09-25 11:15 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +                printf("Buffer size exceeded\r\n");
It **will** be blocked at the moment, as we are using DMA2. But yes, the printf must be removed.

2020-09-25 11:22 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +            printf("\r\nFailed init_resp\r\n");
I am not really happy with this too. DEFAULT_TIMEOUT was used as a safety maximum duration for keeping the reception interrupt enabled, to avoid blocking other threads. Whereas the k_sleep(K_SECONDS(1)) and several others were tuned based on the responses from the SIM800 after testing the GSM states. So, beyond the DEFAULT_TIMEOUT the Rx interrupt will be disabled. 
On the other hand, if I wait k_sleep(K_SECONDS(DEFAULT_TIMEOUT )) in many places, there is a change of WDT reset at various occasions.
I am happy to change this if you have a better suggestion to handle this.

2020-09-25 13:19 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +        memset(resp_buf, 0, sizeof(resp_buf));
Setting index to zero didn't actually solve this. When the UART starts filling the buffer and no null termination happens for the mentioned use case (In case of early exit from the ISR while using the NULL argument), it picks up the previous "OK" in the buffer can misinterpret this. Do you have any suggestion on how to handle this?

2020-09-25 13:23 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +                printf("Buffer size exceeded\r\n");
Got it. DMA2 comes below UART. Thanks

2020-09-25 16:15 UTC, JordanSilverman commented on src/SIM800-AT-Zephyr.cpp
> +    k_sleep(K_SECONDS(1));
But I don't think you will receive "OK" before waking up from sleep mode hence in the previous implementation, we don't wait for OK: https://github.com/lastmileICT/SIM800-AT/blob/f3fa208605f5e6b233f1069c47e636f9d1687987/src/SIM800-AT.cpp#L127

2020-09-25 16:22 UTC, JordanSilverman reviewed
Fine from my side, seems to work functionally and I'm sure things will be cleaner in the future as we move away from mbed.

2020-09-25 16:23 UTC, JordanSilverman approved these changes

2020-09-28 06:25 UTC, martinjaeger requested changes
I'm not completely happy yet, but we may have to proceed as it is in a first step in order to go ahead with the other stuff on the ToDo list. Let's discuss in today's stand-up meeting how we proceed.

2020-09-28 06:25 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
>                  if (ack_message != NULL) { //Decide if an acknowledgement check required
Can this ever get `NULL`?

2020-09-28 06:25 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +        memset(resp_buf, 0, sizeof(resp_buf));
Ah, ok, so you want to make sure it's always zero-terminated even if the ISR stops before getting an ACK. But as far as I can see, the below `resp_buf[0] = '\0'` is enough for that. If the first character in the ACK is zero a comparison between the target ACK message and the actually received message should yield false... or do I misunderstand something?

2020-09-28 06:25 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +    k_sleep(K_SECONDS(2));
I probably don't understand how the part in the charge controller repo works together with this library. So here we set the ISR to continue listening for 85 seconds. How does the main thread in the application make sure it waits for up to 85 seconds? Would it call `enable_bearer` multiple times until below if clause finally returns OK? In that case it makes sense to have a smaller timeout to wait for the response than the maximum timeout in the ISR. But how does the function in the application know when it should finally stop enabling the bearer (i.e. after 85 seconds)?

2020-09-28 06:25 UTC, martinjaeger commented on src/SIM800-AT-Zephyr.cpp
> +            printf("\r\nFailed init_resp\r\n");
So you have to adjust the watchdog to the time the thread might block in worst case condition.

Clean solution would be to keep the `read_resp` command and block until a response was received or it timed out. That's also how it's done in several other Zephyr networking drivers, e.g. the [CAN ISO-TP](https://docs.zephyrproject.org/latest/reference/networking/can_isotp.html#c.isotp_recv). See `ext/can.cpp` for an example.

2020-09-28 13:58 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +            printf("\r\nFailed init_resp\r\n");
The timeout handling will be done as you suggested, but will leave this for improvements, as the communication works fine now.

2020-09-28 13:58 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
>                  if (ack_message != NULL) { //Decide if an acknowledgement check required
This is fixed now. Thanks for finding it.

2020-09-28 13:59 UTC, azeemshatp commented on src/SIM800-AT-Zephyr.cpp
> +    k_sleep(K_SECONDS(2));
At the moment the 85 seconds is a maximum timeout value for the ISR, and usually the responses comes within 1-2 seconds.  If it doesn't, it retries sending another request. So it works fine. But we will change the ISR handler slightly again to handle the timeout processing in the thread as you suggested, which will make it a cleaner solution.

2020-09-28 14:13 UTC, martinjaeger approved these changes
Ok, let's go ahead :)

2020-09-28 14:39 UTC, merged